"""Initial migration

Revision ID: 4fea4c92d28a
Revises: 
Create Date: 2025-04-19 19:45:18.301413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fea4c92d28a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('s_id')
    )
    op.create_table('message',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('msg_role', sa.String(length=20), nullable=False),
    sa.Column('msg_content', sa.Text(), nullable=False),
    sa.Column('msg_created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.s_id'], ),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('sequence',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('seq_id', sa.Integer(), nullable=False),
    sa.Column('seq_role', sa.String(length=50), nullable=False),
    sa.Column('seq_content', sa.Text(), nullable=False),
    sa.Column('seq_created_at', sa.DateTime(), nullable=True),
    sa.Column('seq_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.s_id'], ),
    sa.PrimaryKeyConstraint('seq_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequence')
    op.drop_table('message')
    op.drop_table('session')
    # ### end Alembic commands ###
